logging.level.vn.com.mbbank.adminportal.common.util.RequestLoggingFilter: DEBUG
#logging.level.org.hibernate.orm.jdbc.bind: TRACE
#logging.level.org.hibernate.stat: DEBUG
#logging.level.org.hibernate.SQL: DEBUG
logging:
  config: config/log4j2.xml
server:
  port: 8887
  max-http-request-header-size: 90000
  servlet:
    context-path: /admin-portal/v1
  error:
    include-binding-errors: always
    include-message: always
management:
  security:
    enabled: false
management.endpoints.web.exposure.include: "health,info,prometheus"
management.endpoint.health.show-details: always
management.endpoint.health.probes.enabled: true

springdoc:
  server-url: http://10.1.27.43:9399/admin-portal/v1
  swagger-ui:
    oauth:
      client-id: pap-service
      client-secret: onK7PMkr2mvD2xf8pt74EJ7NtfI1Fe3K

spring:
  application:
    name: admin-portal
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        generate_statistics: true
        query.in_clause_parameter_padding: true
    database-platform: org.hibernate.dialect.OracleDialect
  datasource:
    url: jdbc:oracle:thin:@database-2.cj8o2sc24qmm.ap-southeast-2.rds.amazonaws.com:1521:ORCL?oracle.jdbc.implicitStatementCacheSize=100
    username: admin
    password: ENC(nJ9wWqJfnYC03PwSTu2xPaAKKiOpfD73)
    hikari:
      minimumIdle: 2
      maximumPoolSize: 128
      idleTimeout: 120000
      connectionTimeout: 300000
      leakDetectionThreshold: 300000
  mvc:
    async:
      request-timeout: 120000
  kafka:
    bootstrap-servers: 10.215.109.201:9092,10.215.109.205:9092,10.215.109.206:9092,10.215.109.207:9092,10.215.109.208:9092,10.215.109.209:9092
    properties:
      security.protocol: PLAINTEXT
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
      properties:
        delivery.timeout.ms: 300000
        linger.ms: 100
        batch.size: 6384
        enable.idempotence: true
    consumer:
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      enable-auto-commit: false
    listener:
      concurrency: 4
      ack-mode: MANUAL
  kafka9093:
    bootstrap-servers: 10.215.109.201:9093,10.215.109.205:9093,10.215.109.206:9093,10.215.109.207:9093,10.215.109.208:9093,10.215.109.209:9093
    properties:
      security.protocol: SASL_PLAINTEXT
      sasl.mechanism: SCRAM-SHA-512
      sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="user06" password="XSCueTLxYNJqBDvd";
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
      properties:
        delivery.timeout.ms: 300000
        linger.ms: 100
        batch.size: 6384
        enable.idempotence: true
    consumer:
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      enable-auto-commit: false
    listener:
      concurrency: 4
      ack-mode: MANUAL
redis:
  cluster:
    host: 43.216.3.30:6379
    maxTotal: 10000
    maxIdle: 5
    timeout: 5000
    soTimeOut: 5000
    maxAttempts: 5
    username: chatdst
    password: ENC(HNISvg4pj/w8GpFXZvRzEghvb1/so4g6AU+IPz4Ktm0=)
  keys:
    all-permissions: dev.pap-all-permissions
resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
    instances:
      assignRoleToUser:
        baseConfig: default
        recordFailurePredicate: vn.com.mbbank.adminportal.core.util.predicate.KeycloakInternalRecordFailurePredicate
      revokeRoleFromUser:
        baseConfig: default
        recordFailurePredicate: vn.com.mbbank.adminportal.core.util.predicate.KeycloakInternalRecordFailurePredicate
      getKeycloakUserInfo:
        baseConfig: default
        recordFailurePredicate: vn.com.mbbank.adminportal.core.util.predicate.KeycloakInternalRecordFailurePredicate
      validateToken:
        baseConfig: default
        recordFailurePredicate: vn.com.mbbank.adminportal.core.util.predicate.KeycloakInternalRecordFailurePredicate
      getHcmUserInfo:
        baseConfig: default
        recordFailurePredicate: vn.com.mbbank.adminportal.core.util.predicate.HcmRecordFailurePredicate
      sendOtp:
        baseConfig: default
        recordFailurePredicate: vn.com.mbbank.adminportal.core.util.predicate.OtpRecordFailurePredicate
      verifyOtp:
        baseConfig: default
        recordFailurePredicate: vn.com.mbbank.adminportal.core.util.predicate.OtpRecordFailurePredicate
rate-limit:
  otp:
    verify-limit: 3
    verify-time-seconds: 60
oauth2:
  url: http://10.1.27.43:8831/auth/realms/ms-core/protocol/openid-connect/token
  internal-url: https://keycloak-internal-uat.mbbank.com.vn/auth/realms/internal/protocol/openid-connect/token
authentication.keycloak.jwks-url: https://keycloak-internal-uat.mbbank.com.vn/auth/realms/internal/protocol/openid-connect/certs
keycloak:
  internal:
    url: https://keycloak-internal-uat.mbbank.com.vn/auth
    client-id: pap-service
    client-secret: onK7PMkr2mvD2xf8pt74EJ7NtfI1Fe3K
    client-service-id: dc8fec67-0803-4057-a6d0-59af194098c7
    default-role-id: 4aaed715-f0f3-4898-b07d-a66061c94f07

hcm:
  url: https://hcm-uat.mbbank.com.vn/api
  client-id: partner1
  client-secret: 1hD8W74SxYuvtyA4DFlETbSYlnsuMuab
  oauth2-url:
otp:
  url: http://10.1.27.129:14009/two-factor-authen/v1.0/two-factor-authen
  client-id: pap_user
  client-secret: hDCuMCx262aaihgKCK24qdsUDN1q8vOm
  oauth2-url:

ach-transfer:
  url: http://10.1.27.43:9399/ach-transfer/v1
  proxy-source-prefix: /admin-portal/v1/ach
  client-id: pap_user
  client-secret: hDCuMCx262aaihgKCK24qdsUDN1q8vOm
  oauth2-url:

inhouse-transfer:
  url: http://10.1.27.43:9399/inhouse-transfer/v1
  proxy-source-prefix: /admin-portal/v1/inhouse-transfer
  client-id: pap_user
  client-secret: hDCuMCx262aaihgKCK24qdsUDN1q8vOm
  oauth2-url:

citad-transfer:
  url: http://10.1.27.43:9399/citad-transfer/v1
  proxy-source-prefix: /admin-portal/v1/citad-transfer
  client-id: pap_user
  client-secret: hDCuMCx262aaihgKCK24qdsUDN1q8vOm
  oauth2-url:

routing-transfer:
  url: http://10.1.27.43:9399/routing-transfer/v1
  proxy-source-prefix: /admin-portal/v1
  client-id: pap_user
  client-secret: hDCuMCx262aaihgKCK24qdsUDN1q8vOm
  oauth2-url:

wire-transfer:
  url: http://10.1.27.43:9399/wire-transfer-async/v1
  proxy-source-prefix: /admin-portal/v1/wire-transfer
  client-id: pap_user
  client-secret: hDCuMCx262aaihgKCK24qdsUDN1q8vOm
  oauth2-url:

batch-transfer:
  url: http://10.1.27.43:9399/batch-transfer/v1
  proxy-source-prefix: /admin-portal/v1/batch-transfer
  client-id: pap_user
  client-secret: hDCuMCx262aaihgKCK24qdsUDN1q8vOm
  oauth2-url:
    
ibft-reconcile:
  url: http://10.1.27.43:9399/ibft-reconcile/ibft/portal/v1.0
  proxy-source-prefix: /admin-portal/v1/napas/ibft-reconcile
  client-id: ibft2_user1
  client-secret: WS33xkDodYtyvaer57ZuTIkOar8ilYXD
  oauth2-url:

alias:
  account:
    topic: dev.pap-alias-account
whitelist-account:
  topic: dev.pap-whitelist-account
transfer-channel-config:
  topic: APP_PAP_TRANSFER_CHANNEL_CONFIG_DEV
transfer-channel-bank-config:
  topic: APP_PAP_TRANSFER_CHANNEL_BANK_CONFIG_DEV
transfer-channel-limit:
  topic: APP_PAP_TRANSFER_CHANNEL_LIMIT_DEV
blacklist-account:
  topic: APP_PAP_BLACKLIST_ACCOUNT_DEV
jwt:
  secret: 5G5A2zibrWwmY4xd83RSRYNY9Wcnj60ZAbCdEfGhIjKlMnOpQrStUvWxYz123456
  expiration: 86400000
jasypt:
  encryptor:
    password: MySecretKey
    algorithm: PBEWithMD5AndDES   # mặc định, nên để rõ
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
file:
  upload-dir: uploads

presidioClient.url: http://localhost:5002