package vn.com.mbbank.adminportal.common;

public class SqlStatementTest {
  public static final String PERMISSIONS = """
      truncate table PAP_PERMISSION;
      truncate table PAP_PERMISSION_CATEGORY;
      INSERT INTO PAP_PERMISSION (ID, MODULE, ACTION, DESCRIPTION, BITMASK_VALUE, CREATED_AT) VALUES (1, 'user', 'view', 'View user', 1, systimestamp);
      INSERT INTO PAP_PERMISSION (ID, MODULE, ACTION, DESCRIPTION, BITMASK_VALUE, CREATED_AT) VALUES (2, 'user', 'update', 'Update user', 4, systimestamp);
      INSERT INTO PAP_PERMISSION (ID, MODULE, ACTION, DESCRIPTION, BITMASK_VALUE, CREATED_AT) VALUES (3, 'user', 'delete', 'Delete user', 8, systimestamp);
      INSERT INTO PAP_PERMISSION (ID, MODULE, ACTION, DESCRIPTION, BITMASK_VALUE, CREATED_AT) VALUES (4, 'user', 'insert', 'Insert user', 2, systimestamp);
      INSERT INTO PAP_PERMISSION (ID, MODULE, ACTION, DESCRIPTION, BITMASK_VALUE, CREATED_AT) VALUES (5, 'role', 'view', 'View role', 1, systimestamp);
      INSERT INTO PAP_PERMISSION (ID, MODULE, ACTION, DESCRIPTION, BITMASK_VALUE, CREATED_AT) VALUES (6, 'role', 'update', 'Update role', 4, systimestamp);
      INSERT INTO PAP_PERMISSION (ID, MODULE, ACTION, DESCRIPTION, BITMASK_VALUE, CREATED_AT) VALUES (7, 'role', 'delete', 'Delete role', 8, systimestamp);
      INSERT INTO PAP_PERMISSION (ID, MODULE, ACTION, DESCRIPTION, BITMASK_VALUE, CREATED_AT) VALUES (8, 'role', 'insert', 'Insert role', 2, systimestamp);
      INSERT INTO PAP_PERMISSION (ID, MODULE, ACTION, DESCRIPTION, BITMASK_VALUE, CREATED_AT) VALUES (9, 'role', 'assign', 'Assign role to user', 16, systimestamp);
      INSERT INTO PAP_PERMISSION (ID, MODULE, ACTION, DESCRIPTION, BITMASK_VALUE, CREATED_AT) VALUES (10, 'permission', 'view', 'View permission', 1, systimestamp);
      INSERT INTO PAP_PERMISSION (ID, MODULE, ACTION, DESCRIPTION, BITMASK_VALUE, CREATED_AT) VALUES (11, 'ach-tktg-config', 'view', 'View ach tktg config', 1, systimestamp);
      INSERT INTO PAP_PERMISSION (ID, MODULE, ACTION, DESCRIPTION, BITMASK_VALUE, CREATED_AT) VALUES (12, 'ach-tktg-config', 'insert', 'Insert ach tktg config', 2, systimestamp);
      INSERT INTO PAP_PERMISSION (ID, MODULE, ACTION, DESCRIPTION, BITMASK_VALUE, CREATED_AT) VALUES (13, 'ach-tktg-config', 'update', 'Update ach tktg config', 4, systimestamp);
      INSERT INTO PAP_PERMISSION (ID, MODULE, ACTION, DESCRIPTION, BITMASK_VALUE, CREATED_AT) VALUES (14, 'ach-common-config', 'view', 'View ach common config', 1, systimestamp);
      INSERT INTO PAP_PERMISSION (ID, MODULE, ACTION, DESCRIPTION, BITMASK_VALUE, CREATED_AT) VALUES (15, 'ach-common-config', 'insert', 'Insert ach common config', 2, systimestamp);
      INSERT INTO PAP_PERMISSION (ID, MODULE, ACTION, DESCRIPTION, BITMASK_VALUE, CREATED_AT) VALUES (16, 'ach-common-config', 'update', 'Update ach common config', 4, systimestamp);
      INSERT INTO PAP_PERMISSION (ID, MODULE, ACTION, DESCRIPTION, BITMASK_VALUE, CREATED_AT) VALUES (17, 'bilateral', 'view', 'View bilateral', 1, systimestamp);
      INSERT INTO PAP_PERMISSION (ID, MODULE, ACTION, DESCRIPTION, BITMASK_VALUE, CREATED_AT) VALUES (18, 'routing-whitelist', 'view', 'View routing whitelist', 1, systimestamp);
      INSERT INTO PAP_PERMISSION (ID, MODULE, ACTION, DESCRIPTION, BITMASK_VALUE, CREATED_AT) VALUES (19, 'routing-whitelist', 'update', 'View routing whitelist', 4, systimestamp);
      INSERT INTO PAP_PERMISSION (ID, MODULE, ACTION, DESCRIPTION, BITMASK_VALUE, CREATED_AT) VALUES (20, 'routing-whitelist', 'delete', 'View routing whitelist', 8, systimestamp);
      INSERT INTO PAP_PERMISSION (ID, MODULE, ACTION, DESCRIPTION, BITMASK_VALUE, CREATED_AT) VALUES (21, 'routing-whitelist', 'insert', 'View routing whitelist', 2, systimestamp);
      INSERT INTO PAP_PERMISSION (ID, MODULE, ACTION, DESCRIPTION, BITMASK_VALUE, CREATED_AT) VALUES (22, 'routing-blacklist', 'view', 'View routing blacklist', 1, systimestamp);
      INSERT INTO PAP_PERMISSION (ID, MODULE, ACTION, DESCRIPTION, BITMASK_VALUE, CREATED_AT) VALUES (23, 'routing-blacklist', 'update', 'Update routing blacklist', 4, systimestamp);
      INSERT INTO PAP_PERMISSION (ID, MODULE, ACTION, DESCRIPTION, BITMASK_VALUE, CREATED_AT) VALUES (24, 'routing-blacklist', 'delete', 'Delete routing blacklist', 8, systimestamp);
      INSERT INTO PAP_PERMISSION (ID, MODULE, ACTION, DESCRIPTION, BITMASK_VALUE, CREATED_AT) VALUES (25, 'routing-blacklist', 'insert', 'Insert routing blacklist', 2, systimestamp);
      INSERT INTO PAP_PERMISSION (ID, MODULE, ACTION, DESCRIPTION, BITMASK_VALUE, CREATED_AT) VALUES (26, 'citad-config', 'view', 'View citad-config', 1, systimestamp);
      INSERT INTO PAP_PERMISSION (ID, MODULE, ACTION, DESCRIPTION, BITMASK_VALUE, CREATED_AT) VALUES (27, 'citad-config', 'update', 'Update citad-config', 4, systimestamp);
      INSERT INTO PAP_PERMISSION (ID, MODULE, ACTION, DESCRIPTION, BITMASK_VALUE, CREATED_AT) VALUES (28, 'citad-config', 'delete', 'Delete citad-config', 8, systimestamp);
      INSERT INTO PAP_PERMISSION (ID, MODULE, ACTION, DESCRIPTION, BITMASK_VALUE, CREATED_AT) VALUES (29, 'citad-config', 'insert', 'Insert citad-config', 2, systimestamp);
      INSERT INTO PAP_PERMISSION (ID, MODULE, ACTION, DESCRIPTION, BITMASK_VALUE, CREATED_AT) VALUES (30, 'citad-gateway', 'view', 'View citad-gateway', 1, systimestamp);
      INSERT INTO PAP_PERMISSION (ID, MODULE, ACTION, DESCRIPTION, BITMASK_VALUE, CREATED_AT) VALUES (31, 'citad-gateway', 'update', 'Update citad-gateway', 4, systimestamp);
      INSERT INTO PAP_PERMISSION (ID, MODULE, ACTION, DESCRIPTION, BITMASK_VALUE, CREATED_AT) VALUES (32, 'switching-credit-inter-accounts', 'view', 'View switching-credit-inter-accounts', 1, systimestamp);
      INSERT INTO PAP_PERMISSION (ID, MODULE, ACTION, DESCRIPTION, BITMASK_VALUE, CREATED_AT) VALUES (33, 'switching-credit-inter-accounts', 'insert', 'Insert switching-credit-inter-accounts', 2, systimestamp);
      INSERT INTO PAP_PERMISSION (ID, MODULE, ACTION, DESCRIPTION, BITMASK_VALUE, CREATED_AT) VALUES (34, 'switching-credit-inter-accounts', 'update', 'Update switching-credit-inter-accounts', 4, systimestamp);
      INSERT INTO PAP_PERMISSION (ID, MODULE, ACTION, DESCRIPTION, BITMASK_VALUE, CREATED_AT) VALUES (35, 'switching-credit-inter-accounts', 'delete', 'Delete switching-credit-inter-accounts', 8, systimestamp);
      INSERT INTO PAP_PERMISSION (ID, MODULE, ACTION, DESCRIPTION, BITMASK_VALUE, CREATED_AT) VALUES (36, 'alias-account', 'view', 'View Alias account', 1, systimestamp);
      INSERT INTO PAP_PERMISSION (ID, MODULE, ACTION, DESCRIPTION, BITMASK_VALUE, CREATED_AT) VALUES (37, 'alias-account', 'insert', 'Insert Alias account', 2, systimestamp);
      INSERT INTO PAP_PERMISSION (ID, MODULE, ACTION, DESCRIPTION, BITMASK_VALUE, CREATED_AT) VALUES (38, 'alias-account', 'update', 'Update Alias account', 4, systimestamp);
      INSERT INTO PAP_PERMISSION (ID, MODULE, ACTION, DESCRIPTION, BITMASK_VALUE, CREATED_AT) VALUES (39, 'alias-account', 'delete', 'Delete Alias account', 8, systimestamp);
      INSERT INTO PAP_PERMISSION (ID, MODULE, ACTION, DESCRIPTION, BITMASK_VALUE, CREATED_AT) VALUES (40, 'routing-bank', 'view', 'View routing bank', 1, systimestamp);
      INSERT INTO PAP_PERMISSION (ID, MODULE, ACTION, DESCRIPTION, BITMASK_VALUE, CREATED_AT) VALUES (41, 'error-configs', 'view', 'View error configs', 1, systimestamp);
      INSERT INTO PAP_PERMISSION (ID, MODULE, ACTION, DESCRIPTION, BITMASK_VALUE, CREATED_AT) VALUES (42, 'error-configs', 'insert', 'Insert error configs', 2, systimestamp);
      INSERT INTO PAP_PERMISSION (ID, MODULE, ACTION, DESCRIPTION, BITMASK_VALUE, CREATED_AT) VALUES (43, 'error-configs', 'update', 'Update error configs', 4, systimestamp);
      INSERT INTO PAP_PERMISSION (ID, MODULE, ACTION, DESCRIPTION, BITMASK_VALUE, CREATED_AT) VALUES (44, 'switching-transaction-amount', 'view', 'View transaction amount configs', 1, systimestamp);
      INSERT INTO PAP_PERMISSION (ID, MODULE, ACTION, DESCRIPTION, BITMASK_VALUE, CREATED_AT) VALUES (45, 'switching-transaction-amount', 'insert', 'Insert transaction amount configs', 2, systimestamp);
      INSERT INTO PAP_PERMISSION (ID, MODULE, ACTION, DESCRIPTION, BITMASK_VALUE, CREATED_AT) VALUES (46, 'switching-transaction-amount', 'update', 'Update transaction amount configs', 4, systimestamp);
      INSERT INTO PAP_PERMISSION (ID, MODULE, ACTION, DESCRIPTION, BITMASK_VALUE, CREATED_AT) VALUES (47, 'switching-condition', 'view', 'View switching conditions', 1, systimestamp);
      INSERT INTO PAP_PERMISSION (ID, MODULE, ACTION, DESCRIPTION, BITMASK_VALUE, CREATED_AT) VALUES (48, 'switching-condition', 'update', 'Update switching conditions', 4, systimestamp);
      INSERT INTO PAP_PERMISSION (ID, MODULE, ACTION, DESCRIPTION, BITMASK_VALUE, CREATED_AT) VALUES (49, 'error-code-configs', 'view', 'View error code configs', 1, systimestamp);
      INSERT INTO PAP_PERMISSION (ID, MODULE, ACTION, DESCRIPTION, BITMASK_VALUE, CREATED_AT) VALUES (50, 'error-code-configs', 'insert', 'Insert error code configs', 2, systimestamp);
      INSERT INTO PAP_PERMISSION (ID, MODULE, ACTION, DESCRIPTION, BITMASK_VALUE, CREATED_AT) VALUES (51, 'error-code-configs', 'update', 'Update error code configs', 4, systimestamp);
      INSERT INTO PAP_PERMISSION (ID, MODULE, ACTION, DESCRIPTION, BITMASK_VALUE, CREATED_AT) VALUES (52, 'switching-transaction-amount-fast', 'insert', 'Insert transaction amount', 2, systimestamp);
      INSERT INTO PAP_PERMISSION (ID, MODULE, ACTION, DESCRIPTION, BITMASK_VALUE, CREATED_AT) VALUES (53, 'routing-channel-config', 'view', 'View routing transfer channel configs', 1, systimestamp);
      INSERT INTO PAP_PERMISSION (ID, MODULE, ACTION, DESCRIPTION, BITMASK_VALUE, CREATED_AT) VALUES (54, 'routing-channel-config', 'insert', 'Insert routing transfer channel configs', 2, systimestamp);
      INSERT INTO PAP_PERMISSION (ID, MODULE, ACTION, DESCRIPTION, BITMASK_VALUE, CREATED_AT) VALUES (55, 'routing-channel-config', 'update', 'Update routing transfer channel configs', 4, systimestamp);
      
      insert into PAP_PERMISSION_CATEGORY (PERMISSION_ID, TYPE, SUB_TYPE, CREATED_AT) values (1, 'ADMIN', null, systimestamp);
      insert into PAP_PERMISSION_CATEGORY (PERMISSION_ID, TYPE, SUB_TYPE, CREATED_AT) values (2, 'ADMIN', null, systimestamp);
      insert into PAP_PERMISSION_CATEGORY (PERMISSION_ID, TYPE, SUB_TYPE, CREATED_AT) values (3, 'ADMIN', null, systimestamp);
      insert into PAP_PERMISSION_CATEGORY (PERMISSION_ID, TYPE, SUB_TYPE, CREATED_AT) values (4, 'ADMIN', null, systimestamp);
      insert into PAP_PERMISSION_CATEGORY (PERMISSION_ID, TYPE, SUB_TYPE, CREATED_AT) values (5, 'ADMIN', null, systimestamp);
      insert into PAP_PERMISSION_CATEGORY (PERMISSION_ID, TYPE, SUB_TYPE, CREATED_AT) values (6, 'ADMIN', null, systimestamp);
      insert into PAP_PERMISSION_CATEGORY (PERMISSION_ID, TYPE, SUB_TYPE, CREATED_AT) values (7, 'ADMIN', null, systimestamp);
      insert into PAP_PERMISSION_CATEGORY (PERMISSION_ID, TYPE, SUB_TYPE, CREATED_AT) values (8, 'ADMIN', null, systimestamp);
      insert into PAP_PERMISSION_CATEGORY (PERMISSION_ID, TYPE, SUB_TYPE, CREATED_AT) values (9, 'ADMIN', null, systimestamp);
      insert into PAP_PERMISSION_CATEGORY (PERMISSION_ID, TYPE, SUB_TYPE, CREATED_AT) values (10, 'ADMIN', null, systimestamp);
      insert into PAP_PERMISSION_CATEGORY (PERMISSION_ID, TYPE, SUB_TYPE, CREATED_AT) values (11, 'ADMIN', null, systimestamp);
      insert into PAP_PERMISSION_CATEGORY (PERMISSION_ID, TYPE, SUB_TYPE, CREATED_AT) values (12, 'ADMIN', null, systimestamp);
      insert into PAP_PERMISSION_CATEGORY (PERMISSION_ID, TYPE, SUB_TYPE, CREATED_AT) values (13, 'ADMIN', null, systimestamp);
      insert into PAP_PERMISSION_CATEGORY (PERMISSION_ID, TYPE, SUB_TYPE, CREATED_AT) values (14, 'ADMIN', null, systimestamp);
      insert into PAP_PERMISSION_CATEGORY (PERMISSION_ID, TYPE, SUB_TYPE, CREATED_AT) values (15, 'ADMIN', null, systimestamp);
      insert into PAP_PERMISSION_CATEGORY (PERMISSION_ID, TYPE, SUB_TYPE, CREATED_AT) values (16, 'ADMIN', null, systimestamp);
      insert into PAP_PERMISSION_CATEGORY (PERMISSION_ID, TYPE, SUB_TYPE, CREATED_AT) values (17, 'ADMIN', null, systimestamp);

      insert into PAP_PERMISSION_CATEGORY (PERMISSION_ID, TYPE, SUB_TYPE, CREATED_AT) values (1, 'IT', null, systimestamp);
      insert into PAP_PERMISSION_CATEGORY (PERMISSION_ID, TYPE, SUB_TYPE, CREATED_AT) values (2, 'IT', null, systimestamp);
      insert into PAP_PERMISSION_CATEGORY (PERMISSION_ID, TYPE, SUB_TYPE, CREATED_AT) values (3, 'IT', null, systimestamp);
      insert into PAP_PERMISSION_CATEGORY (PERMISSION_ID, TYPE, SUB_TYPE, CREATED_AT) values (4, 'IT', null, systimestamp);
      insert into PAP_PERMISSION_CATEGORY (PERMISSION_ID, TYPE, SUB_TYPE, CREATED_AT) values (5, 'IT', null, systimestamp);
      insert into PAP_PERMISSION_CATEGORY (PERMISSION_ID, TYPE, SUB_TYPE, CREATED_AT) values (6, 'IT', null, systimestamp);
      insert into PAP_PERMISSION_CATEGORY (PERMISSION_ID, TYPE, SUB_TYPE, CREATED_AT) values (7, 'IT', null, systimestamp);
      insert into PAP_PERMISSION_CATEGORY (PERMISSION_ID, TYPE, SUB_TYPE, CREATED_AT) values (8, 'IT', null, systimestamp);
      insert into PAP_PERMISSION_CATEGORY (PERMISSION_ID, TYPE, SUB_TYPE, CREATED_AT) values (9, 'IT', null, systimestamp);
      insert into PAP_PERMISSION_CATEGORY (PERMISSION_ID, TYPE, SUB_TYPE, CREATED_AT) values (10, 'IT', null, systimestamp);
      insert into PAP_PERMISSION_CATEGORY (PERMISSION_ID, TYPE, SUB_TYPE, CREATED_AT) values (11, 'IT', null, systimestamp);
      insert into PAP_PERMISSION_CATEGORY (PERMISSION_ID, TYPE, SUB_TYPE, CREATED_AT) values (12, 'IT', null, systimestamp);
      insert into PAP_PERMISSION_CATEGORY (PERMISSION_ID, TYPE, SUB_TYPE, CREATED_AT) values (13, 'IT', null, systimestamp);
      insert into PAP_PERMISSION_CATEGORY (PERMISSION_ID, TYPE, SUB_TYPE, CREATED_AT) values (14, 'IT', null, systimestamp);
      insert into PAP_PERMISSION_CATEGORY (PERMISSION_ID, TYPE, SUB_TYPE, CREATED_AT) values (15, 'IT', null, systimestamp);
      insert into PAP_PERMISSION_CATEGORY (PERMISSION_ID, TYPE, SUB_TYPE, CREATED_AT) values (16, 'IT', null, systimestamp);
      insert into PAP_PERMISSION_CATEGORY (PERMISSION_ID, TYPE, SUB_TYPE, CREATED_AT) values (17, 'IT', null, systimestamp);

      insert into PAP_PERMISSION_CATEGORY (PERMISSION_ID, TYPE, SUB_TYPE, CREATED_AT) values (11, 'BUSINESS', null, systimestamp);
      insert into PAP_PERMISSION_CATEGORY (PERMISSION_ID, TYPE, SUB_TYPE, CREATED_AT) values (14, 'BUSINESS', null, systimestamp);
      
      """;
}